### ISSUE TITLE
演示系统已经不能用了吗？

### ISSUE THREAD

**Issue by changbins** [LockGit/gochat#62]
登录报错：
TypeError: Failed to fetch
    at http.tsx:2:12
    at c (regeneratorRuntime.js:86:17)
    at Generator._invoke (regeneratorRuntime.js:66:24)
    at Generator.next (regeneratorRuntime.js:117:21)
    at Cn (asyncToGenerator.js:3:20)
    at i (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21:12
    at Np (http.tsx:1:1)

**Comment by LockGit** [comment]
可以使用，文档中提供了一个在线访问的地址。你如果是本地运行前端ts编译不通过，不大可能是项目代码问题
